### ISSUE TITLE
SSO Login between Laravel app and SuiteCRM

### ISSUE THREAD

**Issue by ivanpellegatta84** [oliverkuchies/onelogin-toolkit#28]
Is possibile set-up a SSO between a Laravel app and SuiteCRM with this package ? 

If no, you think Is possibile do this with Ad-HOC modify ?

Thanks

**Comment by oliverkuchies** [comment]
Hi Ivan,
How do you plan to architect your SSO between SuiteCRM and OneLogin?

If you share your ideal process with me I'll guide you accordingly 😊

**Comment by ivanpellegatta84** [comment]
So, I have a CRM (suiteCRM) and Laravel App for make commercial offerts to
clients (store on CRM).
Agents, will be ables to click on button, in the client module on SuiteCRM,
that open Laravel App for do a commercial offer.

I need that the user had be logged-in, in the Laravel app when change
application, and need that Laravel app can be receive Client ID to make get
API call on CRM and receive Client details

Thanks for any tips

Il dom 11 set 2022, 10:14 Oliver Kucharzewski ***@***.***> ha
scritto:

**Comment by oliverkuchies** [comment]
Hi Ivan,
Should be ok! As long as you have OneLogin as your identity provider you won't have a problem.

My app will allow you to create an app for your integration, and then you can configure it with the OneLogin credentials, and redirect  the user back to the Laravel app when you set the referer URL to your Laravel app..

The user session details will be set in sessions on your Laravel app after successful SSO request with OneLogin.

Let me know how you go 😊

Thanks,
Oliver

**Comment by ivanpellegatta84** [comment]
>
> Ahh ops, I'm Sorry
>
I had undestrand that with your package was possibile do an SSO server 😑

No I Need to do this without external services ...

Thanks for your time, I think will foward with my search 😕
